name: Code Quality

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install System Dependencies (eBPF)
      # Instala o BCC e headers no Ubuntu Runner
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-bpfcc libbpfcc-dev linux-headers-$(uname -r)

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8

    - name: Run Flake8
      run: |
        flake8 src/ --count --show-source --statistics

    - name: Run Pylint
      run: |
        # Adiciona o local de instalação do apt (dist-packages) e o src ao path
        export PYTHONPATH=$PYTHONPATH:/usr/lib/python3/dist-packages:$(pwd)/src
        # Executa a análise de qualidade
        pylint --rcfile=.pylintrc --fail-under=9.5 src/inspector.py src/sys_inspector/*.py